#!/usr/bin/env bash
# This script displays information about subdomains

domain="$1"
subdomain="$2"

if [ -z "$domain" ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

get_subdomain_info() {
    local subdomain="$1"
    local domain="$2"
    local record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {print $4}')
    local destination=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        get_subdomain_info "$sub" "$domain"
    done
else
    get_subdomain_info "$subdomain" "$domain"
fi

