#!/usr/bin/env bash
# It configures Nginx server so that /redirect_me is redirecting to another page

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a default index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Update the Nginx configuration to include the redirect
sudo sed -i '/server_name _;/a \ \ \ \ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart the Nginx service to apply the changes
sudo systemctl restart nginx
