#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Create default HTML file
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Create custom 404 HTML file
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Configure Nginx default site
sed -i '/server_name _;/a \
    rewrite ^\/redirect_me https:\/\/github.com\/Tolulope05 permanent;\n\n\
    error_page 404 \/custom_404.html;\n\
    location = \/custom_404.html {\n\
        root \/usr\/share\/nginx\/html;\n\
        internal;\n\
    }' /etc/nginx/sites-available/default

# Add custom header to Nginx configuration
sed -i '/include \/etc\/nginx\/sites-enabled\/\*;/a \
    add_header X-Served-By "$HOSTNAME";' /etc/nginx/nginx.conf

# Start Nginx service
service nginx start
