#!/usr/bin/env bash
# The script installs and setup haproxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*

sudo echo "ENABLED=1" > /etc/default/haproxy