#!/usr/bin/env bash
# this is a script that ping an IP address passed as an argument
# 5 times,using -z to check if  the first argument "$1"
# is an empty string, it print a usage msg,  if not it ping the IP address
# 5 times using -c to determine the nb of arguments to be send.  

if [[ -z "$1" ]];
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
