#!/usr/bin/env bash
# listens on port  98 on localhost, 
# using nc "netcat" to listen  on port on 98 localhost
# -l is a flag that  say to nc the listen
# an incoming connex  instead of initiating it
nc -l localhost 98
